### ISSUE TITLE
'The specified window isn't an OpenGL window' error on x64 .net framework

### ISSUE THREAD

**Issue by chenxuuu** [opentk/GLWpfControl#103]
OpenTK.GLWpfControl 3.3.0  
OpenTK 3.3.1
.net framework 4.6.2、4.5.2

x86 target works well, but x64 target crash at `OpenTkControl.Start(settings);`

```log
OpenTK.Graphics.GraphicsContextException:“The specified window isn't an OpenGL window”
```

test with readme codes, whole project: [TestGLWpfControl.zip](https://github.com/opentk/GLWpfControl/files/10919352/TestGLWpfControl.zip)

**Comment by NogginBops** [comment]
This error message seems related to SDL, so something seems to be going wrong in the SDL backend. Could ìt be that the SDL dll in your project is only compiled for x86?

**Comment by chenxuuu** [comment]
where is SDL dll? I didn't see it

**Comment by NogginBops** [comment]
That is interesting, from some source you are getting a SDL dll.

Could you try manually updating to OpenTK [3.3.3](https://github.com/opentk/opentk/releases/tag/3.3.3)? You just download that version from nuget and it should work

**Comment by chenxuuu** [comment]
OpenTK 3.3.3 dosen't work too

I search all files in my computer, I found some `sdl.dll` but no one in my path environment variable

**Comment by NogginBops** [comment]
Doesn't need to be in path for dll search to find it, what folders did you find sdl dlls in? Anything related to your project?

**Comment by chenxuuu** [comment]
I found an `SDL2.dll` in `msys2\mingw64\bin` which is in my PATH environment variable  
I remove it and restart vs, same error..

**Comment by chenxuuu** [comment]
yes, it is caused by `sdl2.dll` in my `msys` folder
![图片](https://user-images.githubusercontent.com/10357394/225255508-ecabc836-5694-4d28-b52b-8df1a943cbb9.png)

how to avoid this?
and, why is the loading priority of this dll higher?

**Comment by chenxuuu** [comment]
fixed by set path to an empty string:

```csharp
Environment.SetEnvironmentVariable("path", "");
```
