### ISSUE TITLE
Create a newer DirectX Context than DirectX9

### ISSUE THREAD

**Issue by Iluvatar82** [opentk/GLWpfControl#104]
To be able to debug with Nsight, it would be great if the created DirectX - Context is at least a DirectX11 Context. Otherwise Nsight is not able to help with the debugging.

**Comment by NogginBops** [comment]
I've concluded that is this infeasible as WPF uses DirectX 9 internally and trying to get a DirectX11 context running in tandem with that is either going to go nowhere or be way to much effort.

If anyone wants to try to implement that they are free to do so, but I've already wasted time trying to get thing to happen without luck. But if someone knows something I don't then I'm all ears.
