### ISSUE TITLE
Add the ability to set GLWpfControlSettings parameters within XAML.

### ISSUE THREAD

**Issue by softwareantics** [opentk/GLWpfControl#105]
Having to do the following in the code behind is odd when I should just be able to define this within XAML and simply call `Start()`.

```csharp
this.Start(new GLWpfControlSettings()
{
	MajorVersion = 4,
	MinorVersion = 6,
	GraphicsContextFlags = ContextFlags.ForwardCompatible,
	GraphicsProfile = ContextProfile.Core,
	RenderContinuously = true,
});
```

This would be pretty straightforward; just move the settings properties into `GLWpfControl` and have an overload function that uses the newly created properties. Overloading will ensure that we don't break any existing functionality. The function would likely just be as simple as this:

```csharp
public void Start()
{
    this.Start(new GLWpfControlSettings()
    {
	MajorVersion = this.MajorVersion,
	MinorVersion = this.MinorVersion,
	GraphicsContextFlags = this.GraphicsContextFlags,
	GraphicsProfile = this.GraphicsProfile,
	RenderContinuously = this.RenderContinuously,
    });
}
```

Once a conversation is had about whether it's okay to go ahead with these changes I'd be happy to implement them myself :).

**Comment by NogginBops** [comment]
Yeah definitely think we should expose the control settings in the editor.

Is there no way to adapt the current settings object so we can expose that object in the editor?

**Comment by softwareantics** [comment]
> Yeah definitely think we should expose the control settings in the editor.
> 
> Is there no way to adapt the current settings object so we can expose that object in the editor?

yeah, so @utkumaden has awoken me 😂. We can simply create a public `Settings` property. Pretty sure this will give us a similar solution:

```xaml
    <glwpf:GLWpfControl.Settings>
        <MinorVersion>3</MinorVerrsion>
        <-- etc -->
    </glwpf:GLWpfControl.Settings>
```
