### ISSUE TITLE
GL.Enable(EnableCap.LineSmooth) just makes lines thick?

### ISSUE THREAD

**Issue by TomArrow** [opentk/GLWpfControl#110]
This might be entirely down to me misunderstanding something, please bear with me. I'm just drawing some lines with the old GL.Begin() and GL.Vertex stuff. 

I understand anti-aliasing is hard to implement so I thought I'd try the LineSmooth functionality but I don't get smooth lines, I only get thicker lines. Can someone tell me if I'm doing something wrong here? 

Afaik the line smoothing messes with the depth buffer but I don't even really need the depth buffer, I draw everything in the right order, it's just a GUI I'm making. Is there a way to make this work?

**Comment by NogginBops** [comment]
Anything that is deprecated in the newer versions of OpenGL I would not expect to work, and is likely to be different between GPU vendors.

**Comment by NogginBops** [comment]
Going to close this issue as it's inactive.
