### ISSUE TITLE
Update the `PackageReference` for `OpenTK` to 4.8.0.

### ISSUE THREAD

**Issue by softwareantics** [opentk/GLWpfControl#114]
# Description

I propose we update the `PackageReference` for OpenTK to 4.8.0 as it is the latest stable release.

https://github.com/opentk/GLWpfControl/blob/516bf697e9c786ab3432156d75e1dfca67d3a18c/src/GLWpfControl/GLWpfControl.csproj#L11

We should also likely update the `paket`?

https://github.com/opentk/GLWpfControl/blob/516bf697e9c786ab3432156d75e1dfca67d3a18c/src/GLWpfControl/paket#L26

## The Why

This will _hopefully_ resolve an issue where users are referencing `GLWpfControl` and getting a [NU1608](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1608?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1608)%26rd%3Dtrue) warning about the current reference of `OpenTK` needing to be fixed.

![image](https://github.com/opentk/GLWpfControl/assets/50978201/062a374b-47b7-4ec8-af97-191bb11386fd)

However, I'm a little confused because the NuGet package dependencies show `>= 4.3.0 && < 5.0.0`

![image](https://github.com/opentk/GLWpfControl/assets/50978201/56d3cbf1-a26b-4218-b33f-cae75172bc62)

## The How

I believe just updating the `PackageReference` and uploading a new package with the correct constraints _should_ fix this issue.

**Comment by NogginBops** [comment]
I think that maybe the paket line should be `OpenTK ~> 4 >= 4.8.0`? So that it becomes `>= 4.8.0 && < 5.0.0`, but I'm not 100% sure.

**Comment by NogginBops** [comment]
Fixed with #86
