### ISSUE TITLE
How to enable Antialiasing?

### ISSUE THREAD

**Issue by bhairav-thakkar** [opentk/GLWpfControl#118]
I am trying to use the GLWPFControl and it's performing wonderful!

I could not get an example showing how to enable antialiasing. Where can I find a working example? Or, is there some documentation describing the steps?

Thanks for the awesome control.
Bhairav

**Comment by NogginBops** [comment]
We don't provide a setting to setup backbuffer MSAA currently. You could create your own MSAA framebuffer that you blit to the `GLWpfControl` framebuffer if you really want MSAA.

I've previously looked into adding the MSAA option but I don't think I figured it out. I think #86 will make this easier to implement. Will add this to the `4.3.0` milestone.

**Comment by NogginBops** [comment]
I figured MSAA out, this will be available with #86.
