### ISSUE TITLE
Is it possible to enable stereo with Quad Buffer?

### ISSUE THREAD

**Issue by aptfgazquez** [opentk/GLWpfControl#120]
Hello,

We are using this control in our desktop application and we are planning to support stereo rendering. We've been able to generate a OpenGL context with stereo by creating the context ourselves with:
`GLFW.WindowHint(WindowHintBool.Stereo, true);`

But, of course, the control itself is not using stereo rendering in the "real" DirectX context, so it's not stereo. I guess that for it to work the control must pass two distinct framebuffer ids (one for the left "back buffer" and one for right). This assuming that WPF can handle it..

Is it possible to support it and planned?

Thank you in advance

**Comment by NogginBops** [comment]
I'm not sure it's possible to share stereo framebuffers between DirectX and OpenGL with `WGL_DX_interop` extension, but if it allows for it it might be possible.

**Comment by NogginBops** [comment]
I'm going to make an educated guess here and say that D3D9 probably doesn't support stereoscopic rendering, and even if it did `D3DImage` probably doesn't. So I don't think it is possible to make this feature available unfortunately.
