### ISSUE TITLE
Graphics Context 

### ISSUE THREAD

**Issue by drb4637** [opentk/GLWpfControl#121]
Hi
My application has a few different graphics contexts and I noticed after switching context the glwpf control stops updating. Adding a check inside GLWpfControlRenderer.Render to make sure that the graphics context is current fixes the issue but I was wondering if there was a better way to handle multiple contexts?

**Comment by NogginBops** [comment]
What version of GLWpfControl are you using?
Could you describe your issue in more detail?

How does the updates stop? Does the render function stop being called?

**Comment by NogginBops** [comment]
Changing the thread the GLWpfControls context is current on is going to be pretty problematic as you can't really synchronize when to make it current on the rendering thread. With #86 you are able to setup context sharing between contexts which is likely a better solution.

**Comment by drb4637** [comment]
Hi, sorry for the delayed response. Yea the context sharing seems to fix my issue. Also nice you got MSAA working, gone are the days of bliting the frame buffer :D

**Comment by NogginBops** [comment]
Good to hear! I'll close this issue then. :)
