### ISSUE TITLE
GLWpfControl Does Not Render for MajorVersion=4, MinorVersion=6 Not Even a Clear Blue Background

### ISSUE THREAD

**Issue by anose001** [opentk/GLWpfControl#128]
I was able to follow the [Getting Started section](https://github.com/opentk/GLWpfControl/tree/master?tab=readme-ov-file) and get that setup with a blue background for version MajorVersion=3, MinorVersion=3.

However, it does not seem like I can get GLWpfControl to display a clear blue background for MajorVersion=4, MinorVersion=6 for GLWpfControl v4.3.1 and OpenTK 4.8.2. The display is just black.
OpenGL reports OpenGL Error: InvalidOperation but it is not a FramebufferErrorCode as that is reported as Complete.
Neither Profile = ContextProfile.Core nor Profile = ContextProfile.Compatibility works.

If I revert to GLWpfControl v4.2.3  for MajorVersion=4, MinorVersion=6 then no OpenGL Error is thrown but the screen is still black. Same is true for MinorVersion=1-6 on MajorVersion=4.

Then I cloned the [example projects](https://github.com/opentk/GLWpfControl/tree/master/src/Example) and neither the MainWindow example with Inset nor the TabbedMainWindowTest showed any drawing, only a black background.

Any suggestions on how to set this up properly?

**Comment by NogginBops** [comment]
What hardware are you running this on? Are you sure you have OpenGL 4+ support? Does your gpu+driver support the `NV_DX_interop` extension?

**Comment by jakubwlodarz93** [comment]
Hi, I have a similar issue - I cant render anything with the most up-to-dat version of the nuget (4.3.1) using any of the OpenGL versions - I'm getting only the black screen.
I can get this to render only using nuget 4.2.3 and OpenGL version 3.1 or lower.
I will much appreciate any hints on how I can make it work with the latest version. 
Is there any easy way to check which OpenGL versions are supported on my computer? The same with the NV_DX_interop?

**Comment by NogginBops** [comment]
What graphics cards do both of you run?

@jakubwlodarz93 are you able to run the example project?

**Comment by anose001** [comment]
@NogginBops, I am using a NVIDIA RTX2070 graphics adapter with driver 31.0.15.5212. From what I understand this supports `NV_DX_interop`. 
I also have a Intel(R) UHD Graphics Adapter with driver 31.0.101.2114. 

I did some additional testing:
- for GLWpfControl v4.2.3 both NVIDIA and Intel work.
- for GLWpfControl v4.3.1 only NVIDIA works but **not** Intel.

**Comment by NogginBops** [comment]
Ok that's progress. I introduced a Intel specific bug in the last update.
Only problem is I don't have an intel graphics card to test on...

**Comment by LynJuice** [comment]
Any updates on this?

**Comment by IDXGI** [comment]
I'm having this problem too. 4.2.3 runs correctly, when update to 4.3.0, it have a black screen.
My GPU is AMD integrated graphics.

AMD Radeon(TM) 780M
Driver version: 31.0.14005.1004
Driver Date: 2023/7/20
DirectX Version: 12 (FL 12.1)
![QQ截图20240707170500](https://github.com/opentk/GLWpfControl/assets/50916094/fb2ca26f-5929-48ad-a850-621593ce51be)

I use CodeXL to debug opengl error, the error information is:
![QQ截图20240707161817](https://github.com/opentk/GLWpfControl/assets/50916094/e9c2a7a8-9cdd-47e6-b0d6-2de9ae5f8e82)

It seems like this code have problem, in GLWpfControlRenderer:
![QQ截图20240707170913](https://github.com/opentk/GLWpfControl/assets/50916094/505e134b-2f25-4c9e-a5eb-3a438874a1bb)

**Comment by IDXGI** [comment]
> I'm having this problem too. 4.2.3 runs correctly, when update to 4.3.0, it have a black screen.
> 
> My GPU is AMD integrated graphics.
> 
> 
> 
> AMD Radeon(TM) 780M
> 
> Driver version: 31.0.14005.1004
> 
> Driver Date: 2023/7/20
> 
> DirectX Version: 12 (FL 12.1)
> 
> ![QQ截图20240707170500](https://github.com/opentk/GLWpfControl/assets/50916094/fb2ca26f-5929-48ad-a850-621593ce51be)
> 
> 
> 
> I use CodeXL to debug opengl error, the error information is:
> 
> ![QQ截图20240707161817](https://github.com/opentk/GLWpfControl/assets/50916094/e9c2a7a8-9cdd-47e6-b0d6-2de9ae5f8e82)
> 
> 
> 
> It seems like this code have problem, in GLWpfControlRenderer:
> 
> ![QQ截图20240707170913](https://github.com/opentk/GLWpfControl/assets/50916094/505e134b-2f25-4c9e-a5eb-3a438874a1bb)

@NogginBops

**Comment by NogginBops** [comment]
Ok, great! I actually have access to Ryzen integrated graphics that I can test on. Will investigate this for `4.3.2`.

**Comment by NogginBops** [comment]
So I have tried debugging this and I've started to form a theory on why this might not work.
What is happening is that OpenGL and DirectX are using different devices to create their resources, and then when registering these resources in `NV_DX_interop` it fails because the resources are created on different GPUs.

If I look in the tool [`DxCapsViewer`](https://github.com/microsoft/DxCapsViewer/releases/tag/feb2022) I can see that my nvidia graphics card is listed as a DirectX 9 device but my AMD integrated graphics card only appears in DirectX 10+ APIs.
![image](https://github.com/opentk/GLWpfControl/assets/3778357/6ad61ce9-677b-4560-b1ab-2884684b5db3)

I've not been able to figure out how to make the AMD integrated graphics able to appear in the DirectX 9 device list yet. I've tried updating my drivers, but that didn't do it.

**Comment by IDXGI** [comment]
> 所以我尝试调试它，并开始形成一个理论来解释为什么它可能不起作用。 发生的事情是，OpenGL 和 DirectX 使用不同的设备来创建它们的资源，然后在注册这些资源时`NV_DX_interop`失败，因为这些资源是在不同的 GPU 上创建的。
> 
> 如果我查看该工具，[`DxCapsViewer`](https://github.com/microsoft/DxCapsViewer/releases/tag/feb2022)我可以看到我的 nvidia 显卡被列为 DirectX 9 设备，但我的 AMD 集成显卡仅出现在 DirectX 10+ API 中。 ![图像](https://private-user-images.githubusercontent.com/3778357/346386456-6ad61ce9-677b-4560-b1ab-2884684b5db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjE1MDksIm5iZiI6MTcyMDQyMTIwOSwicGF0aCI6Ii8zNzc4MzU3LzM0NjM4NjQ1Ni02YWQ2MWNlOS02NzdiLTQ1NjAtYjFhYi0yODg0Njg0YjVkYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDhUMDY0NjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzEzNTAxNjU0MDI1ZWY2NzU3ZGI0NTU0YzcyNDFhMDdmNTg5NjdiMGE1OTM2YjQ1ZWMzMTFjMWU0OWE0MDFhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mH_BCdR4Akp1ZuCEptxcBsiRCheoP927jqOayqjqj3o)
> 
> 我还不知道如何让 AMD 集成显卡出现在 DirectX 9 设备列表中。我尝试更新驱动程序，但没有成功。

Is it really because multiple graphics cards are causing the inability to interact? On my laptop, which has only one AMD integrated graphics card, this problem also occurs.

**Comment by NogginBops** [comment]
I see. I do think what I said might still be an issue. 
I guess I should test if the older versions work on my integrated graphics

**Comment by Xerxes004** [comment]
I am experiencing the same issue with 4.3.1 on Intel UHD on my i5-10400. Do you need any more info?

**Comment by insel-maz** [comment]
I also have the problem that version 4.3.1 simply renders black instead of the blue clear color.
However, I don't have integrated graphics, but a dedicated AMD Radeon RX 580.

**Comment by NogginBops** [comment]
@Xerxes004 @insel-maz could you maybe try running the code in #131 and see if it works? It's my current attempt at fixing this issue.

**Comment by Xerxes004** [comment]
@NogginBops Tab 1 now shows up properly but I get a crash when switching to Tab 2. Would you like me to post the stack trace here or in #131?

**Comment by NogginBops** [comment]
> @NogginBops Tab 1 now shows up properly but I get a crash when switching to Tab 2. Would you like me to post the stack trace here or in #131?

So you can see one triangle? You can post the stacktrace in #131

**Comment by Xerxes004** [comment]
> > @NogginBops Tab 1 now shows up properly but I get a crash when switching to Tab 2. Would you like me to post the stack trace here or in #131?
> 
> So you can see one triangle? You can post the stacktrace in #131

Correct, I see one triangle, and the background changes color as expected. I realize my "Tab 1, Tab2" terminology isn't very accurate, so specifically I see the triangle on "Control 1" tab. When clicking "Control 2" is when I see the exception.

**Comment by NogginBops** [comment]
Yeah ok, so multisampling seems to not work on AMD and Intel integrated graphics cards. Not sure why this is.

**Comment by insel-maz** [comment]
> @Xerxes004 @insel-maz could you maybe try running the code in #131 and see if it works? It's my current attempt at fixing this issue.

The issue remains for me. No crash but a black background for tab "Control 1" and tab "Control 2". Tag 4.2.3 is the last version that works for me. My system is quite old (PCIe 2.0), which may be the cause.
