### ISSUE TITLE
Graphics Memory Increase When Resize

### ISSUE THREAD

**Issue by IDXGI** [opentk/GLWpfControl#130]
When I use GLWpfControl, if I keep dragging the borders to resize the window, the GPU's memory continues to grow. And even if I stop resizing, the graphics memory usage remains high.

If it is a normal WPF control, there is no such problem and the memory stays the same when resize the control, without any growth.

Maybe the frame buffer is not released correctly when the size is changed, causing the memory to grow?

Library version: 4.2.3
Hardware Information:
	AMD Radeon(TM) 780M
	Driver version: 31.0.14005.1004
	Driver Date: 2023/7/20
	DirectX Version: 12 (FL 12.1)
	Physical Location: PCI Bus 100, Device 0, Function 0

![0](https://github.com/opentk/GLWpfControl/assets/50916094/7c7ba4d6-70f3-48fb-b298-be655f39f729)
![1](https://github.com/opentk/GLWpfControl/assets/50916094/ea05942e-fb76-40d6-aa89-13dea8fbf37f)

**Comment by NogginBops** [comment]
Will investigate this issue for the next release. It's definitely possible that we have a leak, but looking at the code there is no obvious leak.

**Comment by IDXGI** [comment]
In fact, it will not always increace, when up to 3.7/4.0GB, it will drop to 3.2/4.0GB, then increase.
I use CodeXL to debug, set break when OpenGL error, then resize the window, it immediately hit break point. Maybe something is wrong. But I'm not good at OpenGL programming.
The error is:
![error](https://github.com/opentk/GLWpfControl/assets/50916094/998dda6c-d585-4648-8c3f-9e8b74c104e7)
