### ISSUE TITLE
KeyDown, KeyUp, GotFocus, LostFocus

### ISSUE THREAD

**Issue by markbeach** [opentk/GLWpfControl#31]
Is there something I'm missing in order to use these events in the control?  MouseMove, SizeChanged, and Render work fine.

<glWpfControl:GLWpfControl
                x:Name="OpenTkControl"
                KeyUp="OpenTkControl_KeyUp"
                MouseMove="OpenTkControl_MouseMove"
                LostFocus="OpenTkControl_LostFocus"
                GotFocus="OpenTkControl_GotFocus"
                Loaded="OpenTkControl_Loaded"
                SizeChanged="OpenTkControl_Resize"
                Render="OpenTkControl_OnRender"
            />

**Comment by varon** [comment]
I have no idea, but would welcome a PR if you figure this out.

**Comment by BBoldenow** [comment]
I haven't tried the focus events, but have the same issue with KeyDown and KeyUp. I'll try digging, Varon.

**Comment by NogginBops** [comment]
I'm going to reopen this issue with the goal of having a "proper" fix for events where we don't have to redirect all of them.

**Comment by lazerW0lf** [comment]
@NogginBops see my issue #82 pertaining to a bug with the current redirection scheme.

**Comment by NogginBops** [comment]
#86 fixes this.
