### ISSUE TITLE
Rendering Context MakeCurrent Doesn't Work From Other Threads

### ISSUE THREAD

**Issue by BBoldenow** [opentk/GLWpfControl#40]
Sorry, I can't get to Discord via work, hopefully this is the right place to post -

Currently MakeCurrent doesn't work from other threads for rendering contexts - it throws a resource in use exception. This seems like it'd be worthwhile so you can spawn threads for texture loading and the like that can subsequently request the context. If there is a way to do this currently feel free to let me know (or if there's a better place to post requests).

**Comment by varon** [comment]
This is a perfectly fine place to raise an issue. Thanks for doing so.

Can you try create a context yourself externally and pass that in as part of the settings? It should allow for all sorts of customization as required.

**Comment by DimaS86** [comment]
Hello! I have the same issue and I really need that. I have migrated to GLWpfControl from the old GLControl, which had the same issue, so I recreated the context from the other thread and it worked. However, it is not possible here to create another context from a non-interface thread. I didn't understand how I can create the context externally. Could you please give me some direction to go?
Thanks in advance.

**Comment by BBoldenow** [comment]
Varon, thanks for responding. Life has been a bit crazy, but I'll give that a shot and let you know how it goes. Thanks again!

**Comment by romen-h** [comment]
Even if the context is created on another thread, is it safe to do drawing commands there too? I don't fully understand how the interop with DirectX works but I'd imagine it is unsafe to have OpenGL and DirectX sharing GPU resources on different threads.

**Comment by romen-h** [comment]
Make sure that you are calling `GraphicsContext.MakeCurrent(null)` to "detach" the context from its current thread.  
This allowed me to use the context on another thread with no problems.

**Comment by NogginBops** [comment]
Using context sharing to create separate contexts (`NativeWindow`s) should work fine.
For multiple GLWpfControls, #86 is going to make every GLWpfControl have it's own OpenGL context and will add a `SharedContext` setting so context sharing can be setup between controls.

I'm going to close this issue, feel free to reopen if this is not completely fixed.
