### ISSUE TITLE
WGL:  The driver does not appear to support OpenGL when calling GLWpfControl.Start

### ISSUE THREAD

**Issue by mludlum** [opentk/GLWpfControl#44]
Googling the above error gives me a bunch of Minecraft discussions, so I'm at a loss what I'm doing wrong.  I have a large 64-bit Win Forms app, .NET 5, I've converted from DirectX 9 to OpenTK 4.4.   I have I get the above error at glControl.Start() when I call this method on a class that inherits from ElementHost.   I can run the Example project in this repository fine.  I even ran the Example project  using ES30, OpenTK 4_4, 64 bit, .NET 5 just fine.    I'm unable to use a debugging callback because it wants me to load the bindings or a window first and loading the bindings gives me an error as well.   I'm calling this Start() method in the main form's Load event, but I tried calling it from the main form's constructor as well (which is created from Main()).  

        public bool Start()
        {
            glControl = new GLWpfControl();
            this.Child = glControl;

            //openGLDebugDelegate = new DebugProc(openGLDebugCallback);
            //GL.DebugMessageCallback(openGLDebugDelegate, IntPtr.Zero);
            var settings = new GLWpfControlSettings();
            settings.MajorVersion = 3;
            settings.MinorVersion = 0;
            //settings.GraphicsProfile = ContextProfile.Any;
            glControl.Start(settings);

            RenderContext = new RenderContextGL(this);
            return true;
        }

**Comment by varon** [comment]
Hey @mludlum ! This is for WPF, not Windows Forms!

We have a separate control for WinForms, thanks to @seanofw . You can find this at  https://github.com/opentk/GLControl

**Comment by mludlum** [comment]
What does the WGL error have to do with WPF vs Windows forms?  I saw the other control and tried it.  Similar problems.  Using this control was the recommended method (and using ElementHost) on the opentk hub anyway before the GLControl was brought up to 4.0.   I'll try the other control again and report the error in that hub.  But I believe it was the same error.

**Comment by varon** [comment]
Okay thanks.

**Comment by mludlum** [comment]
There was something in my build output path that was causing the problem.  I had been experimenting with different versions of openTK and/or there were 3rd party libraries also using OpenGL.  Just posting in case someone else runs into this problem.  FYI, the issue occurred with the GLControl as well.
