### ISSUE TITLE
how to handle key events in glWpfControl:GLWpfControl ?

### ISSUE THREAD

**Issue by Ozymandias1** [opentk/GLWpfControl#53]
i tested mouse events(down, up) and test for keyboard events.

mouse events are works great but key events is not triggering.

i want keyboard event firing at only got focused wpfglcontrol.

i already read issue #31 and i think it is not resolved currently.

is this bug or something?

any solution?

best regards.

**Comment by NogginBops** [comment]
Yes this is a bug. I'll close this issue and track it in #31 .
