### ISSUE TITLE
Debugging with e.g. RenderDoc

### ISSUE THREAD

**Issue by Iluvatar82** [opentk/GLWpfControl#60]
Hi there and thank's for the great and fast control.
Is there any way to debug my application with some GFWpfControls in it with a tool like RenderDoc?
Is there any tool I can use to do that? I am not getting any information about the application in all tools I tried and I think maybe it's because of the DX<->OGL interop?

What can I do? I would really like to be able to debug my shaders to see 'what's in there' :).
Thanks

**Comment by NogginBops** [comment]
From what I know there is no way to use RenderDoc with the DX OGL interop extensions.
Tools like Nvidia Nsight should have better support for these extensions, so you might have better luck there.

**Comment by varon** [comment]
Consider setting up a standalone, renderer-only approach using simple OpenGL calls. You can run renderdoc on that. It's a bit of work, but is extremely helpful in the longer run.
