### ISSUE TITLE
Package has dependency to OpenTK v4.3.0 only

### ISSUE THREAD

**Issue by BobLd** [opentk/GLWpfControl#61]
Hi, 

Thanks a lot for the library. Would it be possible to make this package compatible with the latest OpenTK version (v4.6.7 as time of writting). 

Current dependency is setup as `OpenTK (>= 4.3.0 && <4.4.0)`, I guess making it `OpenTK (>= 4.3.0)` would fix that.

Thanks a lot!

**Comment by BobLd** [comment]
Any update?

**Comment by NogginBops** [comment]
Hi! Sorry, it seems like I've not had notifications turned on for this repository, so I've missed a lot of these issues.
There is a PR open that I will review.

**Comment by NogginBops** [comment]
This is fixed with #62 .
