### ISSUE TITLE
Stencil support

### ISSUE THREAD

**Issue by ajkozhevnikov** [opentk/GLWpfControl#64]
Hi, can we expect the new release with stencil support? As I can see, the code is already there, but it was committed after the latest official 4.1.0. Thanks!

**Comment by NogginBops** [comment]
Hi! I just got access to this repo, I do intend to release a new version of this in the not too far future, though I seem to have some problems building the project locally. But I think I'll be able to figure it out.

**Comment by NogginBops** [comment]
I will postpone this to `4.3.0`

**Comment by NogginBops** [comment]
This is fixed in #86
