### ISSUE TITLE
It doesn't work on Parallels Desktop on Mac.

### ISSUE THREAD

**Issue by tictac1234** [opentk/GLWpfControl#68]
Hello.

I just tried the latest version of glWPFControl,
It doesn't work properly on Parallels Desktop on Mac.

Is Parallels Desktop on Mac not supported?
My environment ↓

PC: iMac 2019 4K
GPU : AMD Radeon Pro 560X
Version of Parallels Desktop : 15
Virtual OS : Windows 11 Pro

<img width="768" alt="スクリーンショット 2022-04-15 23 04 01" src="https://user-images.githubusercontent.com/84780155/163584308-46aad269-fa3e-4596-8d43-63711077e1b6.png">

Here is the error message ↓
<img width="501" alt="スクリーンショット 2022-04-15 23 05 05" src="https://user-images.githubusercontent.com/84780155/163584453-a784ac25-b200-4d1a-8770-205444a28896.png">

And, GLWpfControl on Bootcamp may or may not work on some Macs.
(Both are Windows 11 Pro)

◯ It works on Bootcamp of iMac 2019.
(GPU : Radeon Pro 560).

✗ It doesn't work on Bootcamp of Macbook Pro 2015.
(GPU : Intel Iris Pro Graphics).

GLControl using WindowsFormsHost works on Bootcamp,
But there is a flickering problem when moving the View...
So I'd rather use GLWpfControl if possible !

**Comment by tictac1234** [comment]
I forgot to say...The version of GLWpfControl I'm using is the latest 4.1.0.

**Comment by NogginBops** [comment]
What versions of OpenGL does Parallels Desktop support? 
Can you run some sort of tool (for example [OpenGL extension viewer](https://www.realtech-vr.com/home/glview)) and check what versions are available?

**Comment by tictac1234** [comment]
Thank you for your reply.

Parallels Desktop 15 supports up to OpenGL 3.3.
(This is the OpenGL Extensions Viewer running on Parallels Desktop 15.)

<img width="769" alt="スクリーンショット 2022-04-16 11 38 32" src="https://user-images.githubusercontent.com/84780155/163658355-92c8e7e8-7921-44e2-acd8-deab56731df1.png">

In fact, GLControl(OpenGL 3.3) is working↓
<img width="545" alt="スクリーンショット 2022-04-16 11 35 41" src="https://user-images.githubusercontent.com/84780155/163658289-811e023f-aea9-44bf-862a-95d24fde09e3.png">


However, glWpfControl doesn't work.
What could be the cause...?

**Comment by tictac1234** [comment]
I downloaded source code and ran .
It fails at this line ↓ ( DxGlContext.cs )

<img width="584" alt="スクリーンショット 2022-04-16 15 43 55" src="https://user-images.githubusercontent.com/84780155/163664991-180db77d-33e5-4b2d-86db-e73fc39a2df7.png">

**Comment by NogginBops** [comment]
Yeah ok so my guess here is that the directx implementation doesn't support the `wgl_nv_dx_interop` extension that glWpf control  needs to work (wpf uses directx to render, so we need the interop to avoid doing an expensive cpu roundtrip of data).

**Comment by tictac1234** [comment]
You are right, `wgl_nv_dx_interop` was not supported under parallels desktop environment.
I confirmed that in OpenGL Extension Viewer.
I'm sorry, My lack of research caused you inconvenience.
This problem has been resolved. 
Thank you very much !

However, when I tried it in a formal Windows environment, the glWpfControl Example app started, but when I resize it, the screen flickers and does not render correctly...
I only changed the background color from the original code.
After resizing, the background color is completely black.
![キャプチャ](https://user-images.githubusercontent.com/84780155/163751912-73d8ae18-1614-4398-a7b9-64401425887a.PNG)

Test environment ↓.
![キャプチャ](https://user-images.githubusercontent.com/84780155/163751214-2aa84b39-b15c-47c9-a9d4-5a4fbb826a68.PNG)

The same problem occurs on other computers with Intel Graphics (on-board).
Do you have any idea about this flickering ?

**Comment by NogginBops** [comment]
Sorry for the late answer!

I'm not sure about the flickering.
If you open another issue about that issue we could track it.
