### ISSUE TITLE
GL.Enable(EnableCap.ScissorTest); cause rendering area problem

### ISSUE THREAD

**Issue by MingGuys** [opentk/GLWpfControl#69]
just one grid contains one GLWPFControl.But use code like this(code from Learn OpenTK project .https://github.com/opentk/LearnOpenTK):
GL.ClearColor(c);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
            GL.LoadIdentity();
           
            _shader.Use();

            GL.BindVertexArray(_vertexArrayObject);

            
            GL.DrawArrays(PrimitiveType.Triangles, 0, 3);

this will cause rendering area less than true window size.(less width with  90pix,less height with 20pix...).But delete GL.Enable(EnableCap.ScissorTest); have no rendering area problem.
here is my environment.
Windows 10
WPF .net core 3.1 App
OpenTK 4.7.1
GLWpfContrl 4.1.0

**Comment by NogginBops** [comment]
Is this not the same issue as #67 ?

**Comment by MingGuys** [comment]
> Is this not the same issue as #67 ?

yes。same result，but use example code with scissor enable won't cause problem，so...maybe it would miss guide newbie like me。 cause opentk document use new api。but sample code use 3.0 api which is lack document，officially at least。anyway，disable scissor works like charm 。thanks your reply!this control is great。

**Comment by NogginBops** [comment]
Which sample code are you looking at?
If you are looking for OpenTK 4 tutorial code I would recommend looking at this repo https://github.com/opentk/LearnOpenTK

**Comment by MingGuys** [comment]
> Which sample code are you looking at? If you are looking for OpenTK 4 tutorial code I would recommend looking at this repo https://github.com/opentk/LearnOpenTK

Yes.I am reading this tutorial.There is no OpenTK 3 tutorial or API available.So when I update API to OpenTK 4.0 and enabled scissor,then problem occurs.Example code in GLWpfControl uses OpenTK 3.0 API with scissor enabled have no problem.

**Comment by MingGuys** [comment]
> Which sample code are you looking at? If you are looking for OpenTK 4 tutorial code I would recommend looking at this repo https://github.com/opentk/LearnOpenTK

Hi,I made a simple demo.just 9kb.Try this demo.comment GL.Enable(EnableCap.ScissorTest); or not,to see result.
[Demo_Scissor.zip](https://github.com/opentk/GLWpfControl/files/8608006/Demo_Scissor.zip)

**Comment by NogginBops** [comment]
This line of the example makes no sense, and shouldn't be part of that example.
https://github.com/opentk/GLWpfControl/blob/master/src/Example/ExampleScene.cs#L16

It seems like it's a leftover from an earlier example, where the scissor area is actually set
![image](https://user-images.githubusercontent.com/3778357/166442845-ff332488-6311-4af7-8aff-18fce34520f8.png)
