### ISSUE TITLE
Image loads flipped in X and Y

### ISSUE THREAD

**Issue by antithing** [opentk/GLWpfControl#72]
Hi!

I am loading image data using this control, and it works great, except my image is inverted in X and Y.

Is there a simple way to fix this? Code below:

```
public static int LoadTexture()
        {
            byte[] bytes = _gv.GetTextureBytes(frameNum);// grabs image data

            int tex;
            GL.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);

            GL.GenTextures(1, out tex);
            GL.BindTexture(TextureTarget.Texture2D, tex);

        
            GL.CompressedTexImage2D(TextureTarget.Texture2D, 0, InternalFormat.CompressedRgbaS3tcDxt1Ext, width, height, 0, _gv.FrameBytes, bytes);


            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)TextureMinFilter.Linear);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)TextureMagFilter.Linear);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapS, (int)TextureWrapMode.Repeat);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapT, (int)TextureWrapMode.Repeat);

            return tex;
        }

        public static void DrawImage(int image)
        {
            GL.MatrixMode(MatrixMode.Projection);
            GL.PushMatrix();
            GL.LoadIdentity();

     
            GL.Ortho(0, width, 0, height, -1, 1);

            GL.MatrixMode(MatrixMode.Modelview);
          

            GL.PushMatrix();
            GL.LoadIdentity();

            GL.Disable(EnableCap.Lighting);

            GL.Enable(EnableCap.Texture2D);

          
            GL.BindTexture(TextureTarget.Texture2D, image);

            GL.Begin(PrimitiveType.Quads);

            GL.TexCoord2(0, 0);
            GL.Vertex3(0, 0, 0);

            GL.TexCoord2(1, 0);
            GL.Vertex3(width, 0, 0);

            GL.TexCoord2(1, 1);
            GL.Vertex3(width, height, 0);

            GL.TexCoord2(0, 1);
            GL.Vertex3(0, height, 0);

            GL.End();

            GL.Disable(EnableCap.Texture2D);
            GL.PopMatrix();

            GL.MatrixMode(MatrixMode.Projection);
            GL.PopMatrix();

            GL.MatrixMode(MatrixMode.Modelview);
        }



        public static void Render()
        {
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
            texture = LoadTexture();
            DrawImage(texture);

        }
```

**Comment by NogginBops** [comment]
This is because opengl has it's texture origin in the lower left corner instead of the top left corner. You can either modify your UVs, or flip the image data vertically before uploading it, but flipping vertically might not be trivial as pixels are encoded in 4x4 blocks so they need to be internally flipped too

**Comment by antithing** [comment]
Hmm, the texture data comes to me in a compressed format as `byte[] bytes`, not sure if I can adjust it.. 

Can i modify UVs in GL?  Or can i use a shader for this?

**Comment by NogginBops** [comment]
A shader would be the "better" way in that it doesn't use deprecated features. But it's possible to flip the UVs using both immediate mode and modern shaders.

You just have to flip the Y component of your `GL.TexCoord` calls.
```cs
            GL.TexCoord2(0, 1);
            GL.Vertex3(0, 0, 0);

            GL.TexCoord2(1, 1);
            GL.Vertex3(width, 0, 0);

            GL.TexCoord2(1, 0);
            GL.Vertex3(width, height, 0);

            GL.TexCoord2(0, 0);
            GL.Vertex3(0, height, 0);```

**Comment by antithing** [comment]
Thank you! I'll try this. Is there any examples of a simple shader workflow? I am new to GL and a little confused

**Comment by NogginBops** [comment]
Here you can find the go-to tutorial for OpenGL: https://learnopengl.com/
It's in c++, but it's a good idea to learn how to convert c++ opengl code into C# code (not that complicated).

We do have two tutorials written in OpenTK. One is for OpenTK 3 which is a port of learnopengl.com, you can find it here: https://opentk.net/learn/index.html
The other is written with OpenTK 4 and is just heavily commented code and can be found here: https://github.com/opentk/LearnOpenTK

Using a combination of these resources you should be able to get going with modern OpenGL. It's some upfront work, but it's well worth it.

**Comment by NogginBops** [comment]
Closing this as it has been resolved.
