### ISSUE TITLE
Keep aspect ratio when resized?

### ISSUE THREAD

**Issue by antithing** [opentk/GLWpfControl#74]
Hi, I am using this control to ply a video file, and as such need the aspect ratio to stay the same when the window / usercontrol is resized. I am struggling to find a solution for this. Would you be able to point me in the right direction?

Thanks1

**Comment by NogginBops** [comment]
Maybe this could help?
https://stackoverflow.com/questions/288954/how-do-i-keep-aspect-ratio-on-scalable-scrollable-content-in-wpf

**Comment by antithing** [comment]
Hi, and thanks! When i use:

`    <Viewbox Stretch="Uniform">
    <Grid>
        <glWpfControl:GLWpfControl 
            x:Name="OpenTkControl" 
            Render="OpenTkControl_OnRender"/>
    </Grid>
    </Viewbox>
</UserControl>`

The glWpfControl is no longer visible.

with the usual:

`   <Grid>
        <glWpfControl:GLWpfControl 
            x:Name="OpenTkControl" 
            Render="OpenTkControl_OnRender"/>
    </Grid>`

Everything works perfectly.

Thanks again

**Comment by antithing** [comment]
Ah, my mistake, i needed to add width and height to teh Grid.

` <Viewbox Stretch="Uniform">
    <Grid Height="1080" Width="1920">
        <glWpfControl:GLWpfControl 
            x:Name="OpenTkControl" 
            Render="OpenTkControl_OnRender"/>
    </Grid>
    </Viewbox>`


Works great. Thanks again!
