### ISSUE TITLE
Assembly and namespaces not found after install via NuGet

### ISSUE THREAD

**Issue by xdanieldzd** [opentk/GLWpfControl#77]
Hello, I created a new WPF application for testing and am following the Getting Started instructions in the Readme, but am encountering an issue trying to include GLWpfControl in the window.

Adding ``xmlns:glWpfControl="clr-namespace:OpenTK.Wpf;assembly=GLWpfControl"`` to my MainWindow immediately causes error XLS0418 in ``MainWindow.xaml``, i.e. that the assembly "GLWpfControl" could not be found. Additionally, trying to build and run the project regardless then causes error CS0234 to appear from auto-generated code in ``MainWindow.g.i.cs``, i.e. that the type or namespace name "Wpf" couldn't be found in the namespace "OpenTK".

And indeed, IntelliSense offers me all the usual OpenTK namespaces (Audio, Compute, Core, etc.) if I type "OpenTK.[...]" ex. in the window's constructor, but no "Wpf".

I'm using Visual Studio Community 2022 on Windows 10 Pro 21H2, my test project is targeting .NET 6.0, OpenTK and GLWpfControl are the latest stable versions on NuGet (4.7.4 and 4.2.0, respectively).

I'm rather new to WPF, having stuck with WinForms for the longest time, so this might very well be user error. In that case, am I missing something obvious? Is there something else I have to do to reference the assembly correctly, after installing the package? Is the package incompatible with .NET 6.0 and/or VS 2022?

Any help would be very much appreciated.

**Comment by NogginBops** [comment]
This could be the new `4.2.0` release where I might have broken something. Does switching to `4.1.0` fix the issue? 
Could you send me the contents of your `.csproj` project file? or if possible the entire repo so I can repro the issue?

**Comment by Fabi** [comment]
> This could be the new `4.2.0` release where I might have broken something. Does switching to `4.1.0` fix the issue? Could you send me the contents of your `.csproj` project file? or if possible the entire repo so I can repro the issue?

The 4.2.0 release does not contain the compiled dll, that is why. 4.1.0 contains it.

**Comment by NogginBops** [comment]
Should have looked more closely at the finished nuget package before I released it 🤦
Will try get a fix out today, and will unlist 4.2.0 on nuget.

**Comment by NogginBops** [comment]
This is fixed now with `4.2.1`!
