### ISSUE TITLE
Cannot install NuGet package 4.2.1 / incompatible with .NET 6.0?

### ISSUE THREAD

**Issue by xdanieldzd** [opentk/GLWpfControl#78]
While issue #77 now does appear to be fixed, I still cannot use it when targeting .NET 6.0. Any attempt to ex. update the package from 4.1.0 through VS' NuGet Package Manager results in an error while restoring packages (no error code), causing the changes to be rolled back, plus error NU1202, saying that 4.2.1 is incompatible with ``net6.0-windows[...]`` and only supports ``netcoreapp3.1-windows``.

Comparing compatible framework information for [4.1.0](https://www.nuget.org/packages/OpenTK.GLWpfControl/4.1.0#supportedframeworks-body-tab) and [4.2.1](https://www.nuget.org/packages/OpenTK.GLWpfControl/4.2.1#supportedframeworks-body-tab) on NuGet.org, the former is listed as compatible with ``netcoreapp3.1`` (no suffixes) and lists several more _computed_ target frameworks (including ex. ``net6.0-windows``), while the latter only lists ``netcoreapp3.1-windows`` (with the suffix) and no computed target frameworks.

To (hopefully) reproduce:

* Create new WPF application project targeting **.NET 6.0**
* Add OpenTK **4.3.0** and GLWpfControl **4.1.0**
* Follow the Readme's Getting Started section
* Project builds and runs fine

Then:

* Attempt to update GLWpfControl to **4.2.1**
* Encounter aforementioned error NU1202

I guess this is also an issue with the updated build system, maybe (somewhat educated guess) due to it setting the target framework specifically as ``netcoreapp3.1-windows`` instead of the more generic ``netcoreapp3.1``?

**Comment by NogginBops** [comment]
Hmm, yeah this is definitely the new build code.
I thought `netcoreapp3.1-windows` would work fine with `net6-windows`, but apparently not. I'll take a look at how computed target frameworks work as that seems like what we want for this.
Can probably have a fixed package uploaded later today

**Comment by NogginBops** [comment]
I think this is fixed with `4.2.2` now. It does list `net6.0` as compatible. But it seems to also say it's compatible with some target frameworks that it's not compatible with, but that is fine I guess as that is what it did before. When we go to `net5` or `net6` we can fix this.

**Comment by xdanieldzd** [comment]
Yup, appears to be working just fine now, thank you!

.NET 6 with OpenTK 4.7.4 and GLWpfControl 4.2.2:

![Working](https://user-images.githubusercontent.com/7199225/174683007-f5021e38-c22c-4e7e-a48c-38bc18df5b17.png)
